{{- range $group, $params:= .Values.deployments }}
  {{- range $inst, $val:= $params.instances }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $params.prefix }}-{{ $inst }}
  namespace: {{ $.Values.namespace }}
spec:
  selector:
    component: {{ $params.prefix }}.{{ $inst }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
---
  {{- end }}
{{- end }}
