name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        default: 'ci'
        type: choice
        options:
        - ci
        - dev01
        - qa01
        - uat01
        - prod
      build:
        description: 'Build'
        required: true
        type: boolean
        default: true
      test:
        description: 'Unit Tests'
        required: true
        type: boolean
        default: true
      analysis:
        description: 'Static Code Analisys'
        required: true
        type: boolean
        default: true
      package:
        description: 'Package & Upload'
        required: true
        type: boolean
        default: false
      construct:
        description: 'Construct Infractucture'
        required: true
        type: boolean
        default: false
      deploy:
        description: 'Deploy'
        required: true
        type: boolean
        default: false
      e2e:
        description: 'e2e Tests'
        required: true
        default: 'skip'
        type: choice
        options:
        - skip
        - smoke
        - api
        - full
      undeploy:
        description: 'Undeploy'
        required: true
        type: boolean
        default: false
      deconstruct:
        description: 'Deconstruct Infractucture'
        required: true
        type: boolean
        default: false
    
jobs:
  build:
    name: Build & Test
    if: ${{ github.event.inputs.build || github.event.inputs.test || github.event.inputs.analysis || github.event.inputs.package }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install tln cli
        run: |
          npm i -g tln-cli@1.61.0
          echo '{"detach": true}' > '.tlnrc'
          tln --version
      - name: Build
        if: ${{ github.event.inputs.build }}
        run: tln build
      - name: Test
        if: ${{ github.event.inputs.test }}
        run: tln test
      - name: Static Code Analysis (SonarCloud)
        if: ${{ github.event.inputs.analysis }}
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Package
        if: ${{ github.event.inputs.package }}
        run: tln package
  deploy:
    needs: build
    name: Deploy, Validate & Verify
    if: ${{ github.event.inputs.construct || github.event.inputs.deploy || github.event.inputs.e2 != 'skip' || github.event.inputs.undeploy || github.event.inputs.deconstruct }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install tln cli
        run: |
          npm i -g tln-cli@1.61.0
          tln --version    
      - name: Construct Infrastructure
        if: ${{ github.event.inputs.construct }}
        run: tln construct
      - name: Deploy
        if: ${{ github.event.inputs.deploy }}
        run: tln deploy
      - name: e2e Tests
        if: ${{ github.event.inputs.e2 != 'skip' }}
        run: tln e2e
      - name: Undeploy
        if: ${{ github.event.inputs.undeploy }}
        run: tln undeploy
      - name: Deconstruct Infrastructure
        if: ${{ github.event.inputs.deconstruct }}     
        run: tln deconstruct
