name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        required: true
        default: 'ci'
        type: choice
        options:
        - ci
        - dev01
        - qa01
      build:
        description: 'Build'
        required: true
        type: boolean
        default: true
      test:
        description: 'Unit Tests'
        required: true
        type: boolean
        default: true
      analysis:
        description: 'Static Code Analisys'
        required: true
        type: boolean
        default: true
      package:
        description: 'Package & Upload'
        required: true
        type: boolean
        default: false
      construct:
        description: 'Construct Infractucture'
        required: true
        type: boolean
        default: false
      deploy:
        description: 'Deploy'
        required: true
        type: boolean
        default: false
      e2e:
        description: 'e2e Tests'
        required: true
        default: 'skip'
        type: choice
        options:
        - skip
        - smoke
        - api
        - full
      undeploy:
        description: 'Undeploy'
        required: true
        type: boolean
        default: false
      deconstruct:
        description: 'Deconstruct Infractucture'
        required: true
        type: boolean
        default: false
    
jobs:
  build:
    name: Build & Test
    if: ${{ github.event.inputs.build == 'true' || github.event.inputs.test == 'true' || github.event.inputs.analysis == 'true' || github.event.inputs.package == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install tln cli
        run: |
          npm i -g tln-cli@1.61.0
          echo '{"detach": true}' > '.tlnrc'
          tln --version
          tln prereq-app
      - name: Build
        if: ${{ github.event.inputs.build == 'true' }}
        run: tln init-app:build-app
      - name: Test
        if: ${{ github.event.inputs.test == 'true' }}
        run: tln init-app:test-app
      - name: Static Code Analysis (SonarCloud)
        if: ${{ github.event.inputs.analysis == 'true' }}
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Package
        if: ${{ github.event.inputs.package == 'true' }}
        run: |
          docker --version
          echo "${{secrets.DOCKER_REGISTRY}}" > ~/.docker/config.json
          cat ~/.docker/config.json
          tln package-app
  deploy:
    needs: build
    name: Deploy, Validate & Verify
    if: ${{ github.event.inputs.construct == 'true' || github.event.inputs.deploy == 'true' || github.event.inputs.e2e != 'skip' || github.event.inputs.undeploy == 'true' || github.event.inputs.deconstruct == 'true' }}
    runs-on: ubuntu-latest
    env:
      TF_VAR_project_name: project1
      TF_VAR_ii_name: dev
      TF_VAR_env_name: ${{ github.event.inputs.environment }}
      TF_VAR_tenant_name: petramco

      DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}

      TF_VAR_do_region: fra1
      TF_VAR_do_k8s_version: 1.23.9-do.0
      TF_VAR_do_k8s_nodes_min: 1
      TF_VAR_do_k8s_nodes_max: 1
      TF_VAR_do_k8s_nodes_size: s-2vcpu-2gb
      
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install tln cli
        run: |
          npm i -g tln-cli@1.61.0
          echo '{"detach": true}' > '.tlnrc'
          tln --version
          tln install ii/do --depends
      - name: Construct Infrastructure
        if: ${{ github.event.inputs.construct == 'true' }}
        run: tln construct-infr
      - name: Deploy
        if: ${{ github.event.inputs.deploy == 'true' }}
        run: tln deploy-app
      - name: e2e Tests
        if: ${{ github.event.inputs.e2e != 'skip' }}
        run: tln e2e-app
      - name: Undeploy
        if: ${{ github.event.inputs.undeploy == 'true' }}
        run: tln undeploy-app
      - name: Deconstruct Infrastructure
        if: ${{ github.event.inputs.deconstruct == 'true' }}
        run: tln deconstruct-infr
